services:
  nms-landing:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nms_enterprise_landing
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production